testone/signup/urls.py
from django.urls import path
from . import views
app_name = 'signup'
urlpatterns = [
    path('signup/',views. signup_func,name='signup'),
    path('login/',views. login_func,name='login'),
    path('logout/',views. logout_func,name='logout'),
]

testone/testone/urls.py
from django.urls import path, include 
from django.contrib import admin
from django.contrib.staticfiles.urls  import staticfiles_urlpatterns
from django.conf.urls.static import static 
from . import settings
from testoneapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('actors/',include('testoneapp.urls')),
    path('accounts/',include('signup.urls')),
    path('',views.actor_list, name='home'),
   
   
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testone/testoneapp/urls.py
from django.urls import path
from . import views
app_name = 'testoneapp'
urlpatterns = [
    path('', views.actor_list, name='actor_list'),
    path('create/', views.actor_create, name='actor_create'),
    path('<slug:slug>/', views.actor_description, name = 'actor_description'),
    
]

testone/signup/models.py
from django.db import models

# Create your models here.

testone/testoneapp/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Actor(models.Model):
        actorname = models.CharField(max_length=100)
        slug = models.SlugField()
        actor_email = models.EmailField(max_length=100, blank=True,null=True)
        actor_description = models.TextField(max_length=500, blank=True, null=True)
        thumbnail = models.ImageField(default= 'default.png',blank=True, null=True)
        author = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING,blank=True, null=True)
        def __str__(self):
            return self.actorname
    
        def snippet(self):
            return self.actor_description[:50]+"..."

testone/testoneapp/forms.py
from django import forms
from . import models


class CreateActor(forms.ModelForm):
    class Meta:
        model = models.Actor
        fields = ['actorname', 'actor_email', 'actor_description', 'slug', 'thumbnail']

testone/signup/views.py
from asyncio import log
import re
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
# Create your views here.


def signup_func(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            #login user
            user = form.save()
            login(request, user)
            return redirect('/actors/')
    else:
        form  = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def login_func(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('/actors/')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def logout_func(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/actors/')

testone/testoneapp/views.py
from django.shortcuts import redirect, render
from .models import Actor
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def actor_list(request):
    actor_list = Actor.objects.all()
    
    return render(request, 'actor_list.html', {'actor_list': actor_list})

def actor_description(request, slug):
    actor = Actor.objects.get(slug=slug)
    return render(request, 'actor_description.html', {'actor': actor})


@login_required(login_url='signup:login')
def actor_create(request):
    if request.method == 'POST':
      form = forms.CreateActor(request.POST, request.FILES)
      if form.is_valid():
          #save article to database
          Instance = form.save(commit='False')
          Instance.author = request.user
          Instance.save()
          
          return redirect('testoneapp:actor_list')
    else:
        form = forms.CreateActor
    return render(request, 'actor_create.html', {'form': form})

testone/signup/templates/login.html
{% extends 'base_template.html' %}

{% block content %}


<h2>Login Form</h2>
<form action="{% url 'signup:login' %}" method="POST">
{% if request.GET.next %}
<input type="hidden" name="next" value={{request.GET.next}} />

{% endif %}

    {% csrf_token %}
{{form}}
<input type="submit" value="Login" />
</form>

{% endblock content %}

testone/signup/templates/signup.html
{% extends 'base_template.html' %}

{% block content %}

<h2>Testing Signup page</h2>
<form  method="post" action="/accounts/signup/">
{% csrf_token %}
    {{form}}
<input type="submit" value="Signup" />
</form>
{% endblock content %}

testone/templates/base_template.html
{%load static%}

<html>
<head>
<meta charset= "utf-8">
<title>Actors</title>
<link rel="stylesheet" href="{%static 'style.css'%}">
</head>
<body>
    <h1><a href="{% url 'home' %}"><img src="{% static 'testlogo.jpg' %}"></a></h1>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li><form action= {% url 'signup:logout' %} method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form></li>
            <li><a href="{% url 'testoneapp:actor_create' %}">Create Article</a></li>
            {% else %}
            <li><a href="{% url 'signup:login' %}">Login</a></li>
            <li><a href=" {% url 'signup:signup'%}">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
    <h1>Actors</h1>
    <div class="wrapper">
    {% block content %}
    {% endblock%}

</div>

</body>


</html>

testone/testoneapp/templates/actor_create.html
{% extends 'base_template.html' %}

{% block content %}

<h2>Create awesome new actor</h2>
<form action= {% url 'testoneapp:actor_create'%} method="post" enctype="multipart/form-data">
{% csrf_token %}
<input type="submit" value="Create" />
    {{form}}
</form>

{% endblock content %}

testone/testoneapp/templates/actor_description.html
{% extends 'base_template.html' %}
{% block content %}
<div class = actor>
    <img src="{{actor.thumbnail.url}}" width="100" height="100"/>
    <h1>{{actor.actorname}}</h1>
</div>
<div class = description>

<h2>{{actor.actor_description}}</h2>

</div>



{% endblock %}

testone/testoneapp/templates/actor_list.html
{%extends 'base_template.html'%}
{% block content %}
<div class= "actors">
 {% for actor in actor_list %}
    <div class actordata>
        <h2><a href="{% url 'testoneapp:actor_description' actor.slug %}">{{actor.actorname}}</a></h2>
        <h2>
            {{actor.actor_email}}    </h2>
           <h2>{{actor.snippet}}</h2>


    </div>
 {% endfor %}
</div>
{% endblock %}